name: javascript / format

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - name: Use Node.js LTS (16.x)
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561
        with:
          node-version: '16'
      - name: Install project development dependencies
        run: npm i
      - name: 'Verify formatting of all files'
        run: ./bin/check-formatting.sh
